<a href="https://colab.research.google.com/github/dmortalla/AI-Coding-with-GitHub-Copilot/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals
Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

This is my first Pytorch notebook on Colab.

In [1]:
print("Hello, I'm excited to learn PyTorch!")

Hello, I'm excited to learn PyTorch!


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.0+cu121


## I. Intro to Tensors
### A. Creating Tensors
PyTorch tensors are created using torch.Tensor().

Docs:
1. https://pytorch.org/tutorials/beginner/introyt/tensors_deeper_tutorial.html

2. https://pytorch.org/docs/stable/tensors.html

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Check dimension
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([5, 6])
vector

tensor([5, 6])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
matrix = torch.tensor([[2, 5], [1, 9]])
matrix

tensor([[2, 5],
        [1, 9]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
matrix[0]

tensor([2, 5])

In [14]:
matrix[1]

tensor([1, 9])

In [15]:
bars = torch.tensor([[1, 5, -2, 6], [4, 0, -1, 7], [10, -5, 4, 8]])
bars

tensor([[ 1,  5, -2,  6],
        [ 4,  0, -1,  7],
        [10, -5,  4,  8]])

In [16]:
bars.ndim

2

In [17]:
bars.shape

torch.Size([3, 4])

In [18]:
circles = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
circles

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
circles.ndim

3

In [20]:
circles.shape

torch.Size([1, 3, 3])

In [21]:
circles[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [22]:
circles[0][0]

tensor([1, 2, 3])

In [23]:
circles[0][1]

tensor([3, 6, 9])

In [24]:
circles[0][2]

tensor([2, 4, 5])

In [25]:
circles[0].shape

torch.Size([3, 3])

### Random Tensors
Why random tensors?

Random tensors are important because many neural networks learn by starting with tensors full of random numbers then adjust these numbers to represent better the data.

The default tensor dtype is float32. Tensor datatype is one of the 3 big potential error causes you can have with tensors. The others are shape and device.

Documentation: https://pytorch.org/docs/stable/generated/torch.rand.html


In [26]:
# Create a random tensor of decimals between 0 and 1 of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.size()

(tensor([[0.6941, 0.2015, 0.7347, 0.0879],
         [0.8236, 0.1171, 0.6287, 0.4893],
         [0.7720, 0.0399, 0.3201, 0.7509]]),
 torch.float32,
 torch.Size([3, 4]),
 2,
 torch.Size([3, 4]))

In [27]:
# Create a random tensor of shape (3, 2, 4)
random_tensor1 = torch.rand(3, 2, 4)
random_tensor1, random_tensor1.dtype, random_tensor1.shape, random_tensor1.ndim, random_tensor1.size()

(tensor([[[0.7297, 0.5998, 0.0732, 0.9325],
          [0.6996, 0.1545, 0.1496, 0.9025]],
 
         [[0.0642, 0.6082, 0.6988, 0.6731],
          [0.9086, 0.1915, 0.8160, 0.1192]],
 
         [[0.0334, 0.8029, 0.6728, 0.6240],
          [0.9385, 0.2618, 0.2376, 0.3519]]]),
 torch.float32,
 torch.Size([3, 2, 4]),
 3,
 torch.Size([3, 2, 4]))

In [28]:
# Create a random tensor of shape like an image tensor (height, width, color channels)
random_color_tensor = torch.rand(224, 224, 3)
random_color_tensor

tensor([[[0.7504, 0.2411, 0.6909],
         [0.6981, 0.9233, 0.1719],
         [0.8816, 0.5854, 0.5097],
         ...,
         [0.4158, 0.7230, 0.5889],
         [0.7381, 0.2667, 0.9195],
         [0.0506, 0.3743, 0.2974]],

        [[0.0186, 0.5135, 0.4624],
         [0.3210, 0.1706, 0.6356],
         [0.0040, 0.6487, 0.9281],
         ...,
         [0.7175, 0.7784, 0.6674],
         [0.2376, 0.5327, 0.7928],
         [0.2766, 0.8402, 0.5706]],

        [[0.8080, 0.5085, 0.3764],
         [0.3038, 0.6429, 0.1722],
         [0.1631, 0.5980, 0.4037],
         ...,
         [0.4474, 0.7872, 0.7517],
         [0.2906, 0.1576, 0.9519],
         [0.3644, 0.6212, 0.2099]],

        ...,

        [[0.4035, 0.5842, 0.0189],
         [0.4377, 0.4782, 0.5854],
         [0.3098, 0.9725, 0.9844],
         ...,
         [0.5299, 0.8462, 0.0836],
         [0.1206, 0.7479, 0.6638],
         [0.3375, 0.5422, 0.7116]],

        [[0.4197, 0.9545, 0.4179],
         [0.2496, 0.0546, 0.7038],
         [0.

In [29]:
# Create a random tensor of integers with shape (3, 4)
random_tensor2 = torch.randint(15, size=(3, 2, 4))
random_tensor2, random_tensor2.dtype, random_tensor2.shape, random_tensor2.ndim, random_tensor2.size()

(tensor([[[ 5,  2,  2,  1],
          [ 2, 14, 14,  1]],
 
         [[13,  2, 10,  9],
          [12, 11, 14,  0]],
 
         [[ 2,  1, 13, 11],
          [ 9,  7,  7,  9]]]),
 torch.int64,
 torch.Size([3, 2, 4]),
 3,
 torch.Size([3, 2, 4]))

### Tensors of Zeros and Ones

In [30]:
# Create a tensor of all zeros
zeros = torch.zeros(3, 4)   # Or zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype, zeros.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32,
 2)

In [31]:
# Create a tensor of all ones
ones = torch.ones(size=(2, 5))   # Or ones = torch.ones(2, 5)
ones, ones.dtype, ones.ndim

(tensor([[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]),
 torch.float32,
 2)

### Creating a range of tensors and tensors-like
The .arange() method use the half-open set [LL, UL).

In [32]:
# Use torch.arange() for elements 0-9
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# Use torch.arange() for elements 1-10
tensor_one_to_ten = torch.arange(1, 11)
tensor_one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# Creating a tensor like another tensor (same shape)
ten_ones = torch.ones_like(input=tensor_one_to_ten)
ten_zeros = torch.zeros_like(input=tensor_one_to_ten)
ten_ones, ten_zeros

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

## Tensor Datatypes

Three important tensor parameters are:
1. dtype
2. device
3. requires_grad

In [35]:
# Default float32 tensors (holds 32 bits in memory)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)